[cpu]
cputype=auto
cycles=fixed 500000
core=dynamic_x86

[sblaster]
sbtype=sb16vibra

[dosbox]
machine=svga_s3vision968
memsize=16

[video]
vmemsize=16
vesa modelist width limit=0
vesa modelist height limit=0